/* Family Book Guest Demo: safe fictional adapter loaded before the production app. */
(function(){
 const me={backend:'demo',needsSetup:false,supabaseUserId:'demo-user',email:'guest@familybook.demo',name:'Daniel Williams',family:'Williams Family',familyId:'demo-williams-family',memberId:'demo-daniel',membershipId:'demo-membership',role:'admin',photo:''};
 const members=[['robert','Robert','Williams','Male','Grandfather','1954-03-18'],['grace','Grace','Williams','Female','Grandmother','1957-08-09'],['daniel','Daniel','Williams','Male','Father','1984-05-11'],['sarah','Sarah','Williams','Female','Mother','1986-11-02'],['olivia','Olivia','Williams','Female','Aunt','1988-02-22'],['ethan','Ethan','Williams','Male','Son','2012-07-14'],['mia','Mia','Williams','Female','Daughter','2016-10-12']].map(x=>({id:'demo-'+x[0],person_id:'demo-'+x[0],first:x[1],firstName:x[1],first_name:x[1],last:x[2],surname:x[2],gender:x[3],sex:x[3],relation:x[4],relationship:x[4],dob:x[5],date_of_birth:x[5],familyId:'demo-williams-family',family_id:'demo-williams-family'}));
 const relationships=[{type:'spouse',a:'demo-robert',b:'demo-grace',marriageDate:'1978-09-28'},{type:'spouse',a:'demo-daniel',b:'demo-sarah',marriageDate:'2009-11-21'},{type:'parent',parent:'demo-robert',child:'demo-daniel'},{type:'parent',parent:'demo-grace',child:'demo-daniel'},{type:'parent',parent:'demo-robert',child:'demo-olivia'},{type:'parent',parent:'demo-grace',child:'demo-olivia'},{type:'parent',parent:'demo-daniel',child:'demo-ethan'},{type:'parent',parent:'demo-sarah',child:'demo-ethan'},{type:'parent',parent:'demo-daniel',child:'demo-mia'},{type:'parent',parent:'demo-sarah',child:'demo-mia'}];
 window.FB_DEMO_MODE=true;window.FB_DEMO={user:me,members,relationships};
 window.FB_AUTH={init:async()=>me,refresh:async()=>me,get:()=>me,current:()=>me,isAuthenticated:()=>true,update:p=>Object.assign(me,p||{}),logout:async()=>location.href='../',familyStorageKey:()=>'demo_williams_family',pendingInvite:()=>'',renderSetup:()=>{}};
 window.FB_DATA={family:'Williams Family',memories:[['Beach Day','Williams family'],['Old family album','Three generations'],['Sunday together','Family memory']],events:[['04','OCT','Family Braai','Family event'],['12','OCT',"Mia's Birthday",'Birthday'],['21','NOV','Daniel & Sarah Anniversary','Anniversary']],people:members.map(m=>m.first)};
 window.FB_FAMILY_DATA={reload:async()=>({members,relationships}),load:async()=>({members,relationships}),get:()=>({members,relationships}),members:()=>members,relationships:()=>relationships,save:async()=>({demo:true}),remove:async()=>({demo:true})};
 document.documentElement.dataset.demoMode='true';
})();