(function(){
  const providers=new Map();let activeProvider="supabase";let config={provider:"supabase"};const B2_URL_CACHE_KEY="fb_b2_signed_urls_v1";const b2UrlCache=new Map();
  function loadB2UrlCache(){try{const raw=JSON.parse(sessionStorage.getItem(B2_URL_CACHE_KEY)||"{}"),now=Date.now();Object.entries(raw||{}).forEach(([p,i])=>{if(i?.url&&Number(i.expiresAt)>now+60000)b2UrlCache.set(p,{url:String(i.url),expiresAt:Number(i.expiresAt)})})}catch(_){}}
  function saveB2UrlCache(){try{const now=Date.now(),out={};b2UrlCache.forEach((i,p)=>{if(i?.url&&Number(i.expiresAt)>now+60000)out[p]=i});sessionStorage.setItem(B2_URL_CACHE_KEY,JSON.stringify(out))}catch(_){}}
  function getCachedB2Url(path){const i=b2UrlCache.get(String(path));if(!i)return"";if(Number(i.expiresAt)<=Date.now()+60000){b2UrlCache.delete(String(path));return""}return i.url||""}
  function cacheB2Urls(entries,expiresIn){const ttl=Math.max(60,Number(expiresIn)||7200),expiresAt=Date.now()+Math.max(60,ttl-300)*1000;Object.entries(entries||{}).forEach(([p,u])=>{if(u)b2UrlCache.set(p,{url:String(u),expiresAt})});saveB2UrlCache()}
  loadB2UrlCache();const uniquePaths=paths=>[...new Set((paths||[]).filter(Boolean).map(String))];
  function requireProvider(){const p=providers.get(activeProvider);if(!p)throw new Error(`Media provider "${activeProvider}" is not registered.`);return p}
  function registerProvider(name,adapter){if(!name||!adapter)throw new Error("A media provider name and adapter are required.");["upload","remove","download","signedUrlMap"].forEach(fn=>{if(typeof adapter[fn]!=="function")throw new Error(`Media provider "${name}" is missing ${fn}().`)});providers.set(String(name),adapter);return api}
  function configure(next={}){config={...config,...next};if(next.provider)useProvider(next.provider);return{...config,provider:activeProvider}}
  function useProvider(name){const key=String(name||"").trim();if(!providers.has(key))throw new Error(`Media provider "${key}" is not registered.`);activeProvider=key;config.provider=key;window.dispatchEvent(new CustomEvent("familybook:media-provider-changed",{detail:{provider:key}}));return key}
  const providerName=()=>activeProvider;function providerInfo(){const p=requireProvider();return{provider:activeProvider,...(typeof p.info==="function"?p.info():{})}}
  async function upload(path,blob,options={}){if(!path)throw new Error("A storage path is required.");if(!(blob instanceof Blob))throw new Error("A Blob/File is required for upload.");return requireProvider().upload(String(path),blob,options)}
  async function remove(paths,options={}){const list=uniquePaths(paths);if(!list.length)return{removed:[]};try{return await requireProvider().remove(list,options)}catch(err){if(options?.silent){console.warn("Family Book media cleanup:",err?.message||err);return{removed:[],error:err}}throw err}}
  async function download(path){if(!path)throw new Error("A storage path is required.");return requireProvider().download(String(path))}
  async function signedUrlMap(paths,expiresIn=7200){const list=uniquePaths(paths);if(!list.length)return new Map();return requireProvider().signedUrlMap(list,expiresIn)}
  async function getSignedUrl(path,expiresIn=7200){if(!path)return"";const map=await signedUrlMap([path],expiresIn);return map.get(String(path))||""}
  async function healthCheck(){const p=requireProvider();return typeof p.healthCheck==="function"?p.healthCheck():{ok:true,...providerInfo()}}
  const supabaseProvider={client(){const c=window.FB_SUPABASE?.client;if(!c)throw new Error("Supabase is not ready.");return c},bucket(){return window.FB_SUPABASE_CONFIG?.mediaBucket||"family-media"},info(){return{bucket:this.bucket(),clientReady:!!window.FB_SUPABASE?.client}},async upload(path,blob,options={}){const{error}=await this.client().storage.from(this.bucket()).upload(path,blob,{contentType:options.contentType||blob.type||"application/octet-stream",upsert:options.upsert===true,cacheControl:String(options.cacheControl||"3600")});if(error)throw new Error(error.message||"Could not upload family media.");return{provider:"supabase",bucket:this.bucket(),path}},async remove(paths){const{data,error}=await this.client().storage.from(this.bucket()).remove(paths);if(error)throw new Error(error.message||"Could not remove family media.");return{provider:"supabase",removed:paths,data}},async download(path){const{data,error}=await this.client().storage.from(this.bucket()).download(path);if(error)throw new Error(error.message||"Could not download private family media.");return data},async signedUrlMap(paths,expiresIn){const{data,error}=await this.client().storage.from(this.bucket()).createSignedUrls(paths,expiresIn);if(error)throw new Error(error.message||"Could not open private family media.");const map=new Map();(data||[]).forEach((item,i)=>{const path=item.path||paths[i];if(path&&item.signedUrl)map.set(path,item.signedUrl)});return map}};
  const b2Provider={functionName:"b2-media-sign",client(){const c=window.FB_SUPABASE?.client;if(!c)throw new Error("Supabase is not ready.");return c},info(){return{functionName:this.functionName,primaryStorage:"Backblaze B2",legacyReadFallback:"Supabase Storage"}},async invoke(action,payload={}){const{data,error}=await this.client().functions.invoke(this.functionName,{body:{action,...payload}});if(error)throw new Error(error.message||`B2 ${action} request failed.`);if(data?.error)throw new Error(data.error);return data||{}},async healthCheck(){return this.invoke("health")},
    async upload(path,blob,options={}){const contentType=options.contentType||blob.type||"application/octet-stream";const put=async()=>{const signed=await this.invoke("sign-upload",{path,contentType});if(!signed?.url)throw new Error("B2 did not return an upload URL.");const response=await fetch(signed.url,{method:"PUT",headers:{"Content-Type":signed.contentType||contentType},body:blob});if(!response.ok){const detail=await response.text().catch(()=>"");throw new Error(`B2 upload failed (${response.status})${detail?`: ${detail.slice(0,180)}`:""}`)}return{provider:"backblaze-b2",path}};try{return await put()}catch(first){if(first instanceof TypeError||/failed to fetch|networkerror|load failed/i.test(String(first?.message||first))){console.warn("B2 browser upload blocked; refreshing bucket CORS and retrying once.");try{await this.invoke("configure-cors");await new Promise(r=>setTimeout(r,700));return await put()}catch(second){console.error("B2 upload retry failed:",second);throw new Error(`Cover upload could not reach media storage. ${second?.message||first?.message||"Please try again."}`)}}throw first}},
    async signedUrlMap(paths,expiresIn){const list=uniquePaths(paths);if(!list.length)return new Map();const map=new Map(),uncached=[];list.forEach(path=>{const cached=getCachedB2Url(path);if(cached)map.set(path,cached);else uncached.push(path)});if(uncached.length){const signed=await this.invoke("sign-downloads",{paths:uncached,expiresIn:Number(expiresIn)||7200});cacheB2Urls(signed?.urls||{},signed?.expiresIn||expiresIn||7200);Object.entries(signed?.urls||{}).forEach(([p,u])=>{if(u)map.set(p,String(u))})}return map},async download(path){const map=await this.signedUrlMap([path],7200),url=map.get(path);if(!url)throw new Error("This family media file could not be found.");const response=await fetch(url);if(!response.ok)throw new Error(`Could not download family media (${response.status}).`);return response.blob()},async remove(paths){const list=uniquePaths(paths);if(!list.length)return{provider:"backblaze-b2",removed:[]};const result=await this.invoke("delete",{paths:list});list.forEach(path=>b2UrlCache.delete(path));saveB2UrlCache();return{provider:"backblaze-b2",removed:Array.isArray(result?.deleted)?result.deleted:list}}};
  const api={registerProvider,configure,useProvider,providerName,providerInfo,upload,remove,download,signedUrlMap,getSignedUrl,healthCheck};registerProvider("supabase",supabaseProvider);registerProvider("backblaze-b2",b2Provider);api.rollbackToSupabase=()=>useProvider("supabase");api.useBackblaze=()=>useProvider("backblaze-b2");api.clearSignedUrlCache=()=>{b2UrlCache.clear();try{sessionStorage.removeItem(B2_URL_CACHE_KEY)}catch(_){}};window.FB_MEDIA=api;useProvider("backblaze-b2");
})();